[tool.isort]
profile = "black"
multi_line_output = 3

[tool.black]
target-version = ['py37']

[tool.pylint.MASTER]
reports = 'no'
disable = [
  "missing-docstring",
  "duplicate-code",
  "invalid-name",
  "line-too-long",
  "unnecessary-pass",
  "redefined-outer-name",
  "too-few-public-methods",
  "unspecified-encoding",
  "too-many-branches",
  "too-many-statements",
  "too-many-locals",
  "import-outside-toplevel",
  "arguments-differ",
  "unused-argument",
  "too-many-return-statements",
  "logging-fstring-interpolation",
  "f-string-without-interpolation",
  "fixme",
  "too-many-arguments",
  "raise-missing-from",
  "no-else-return",
  "too-many-instance-attributes",
]

[tool.ruff]
line-length = 9001
