FEEDBACK_LEVEL_RESTRICTED = "RESTRICTED"
FEEDBACK_LEVEL_FULL = "FULL"
FEEDBACK_LEVELS = [FEEDBACK_LEVEL_RESTRICTED, FEEDBACK_LEVEL_FULL]

SCORE_MODE_MAX_TOKENED_LAST = "MAX_TOKENED_AND_LAST"
SCORE_MODE_SUM_SUBTASK_BEST = "SUM_SUBTASK_BEST"
SCORE_MODE_MAX = "MAX"
SCORE_MODES = [
    SCORE_MODE_MAX_TOKENED_LAST,
    SCORE_MODE_SUM_SUBTASK_BEST,
    SCORE_MODE_MAX,
]

SCORE_TYPE_GROUP_MIN = "GROUP_MIN"
SCORE_TYPE_GROUP_MUL = "GROUP_MUL"
SCORE_TYPE_GROUP_THRESHOLD = "GROUP_THRESHOLD"
SCORE_TYPE_SUM = "SUM"
SCORE_TYPES = [
    SCORE_TYPE_GROUP_MIN,
    SCORE_TYPE_GROUP_MUL,
    SCORE_TYPE_GROUP_THRESHOLD,
    SCORE_TYPE_SUM,
]

TASK_TYPE_BATCH = "BATCH"
TASK_TYPE_OJUZ = "OJUZ"
TASK_TYPE_OUTPUT_ONLY = "OUTPUT_ONLY"
TASK_TYPE_COMMUNICATION = "COMMUNICATION"
TASK_TYPES = [
    TASK_TYPE_BATCH,
    TASK_TYPE_OJUZ,
    TASK_TYPE_OUTPUT_ONLY,
    TASK_TYPE_COMMUNICATION,
]

TOKEN_MODE_DISABLED = "DISABLED"
TOKEN_MODE_FINITE = "FINITE"
TOKEN_MODE_INFINITE = "INFINITE"
TOKEN_MODES = [
    TOKEN_MODE_DISABLED,
    TOKEN_MODE_FINITE,
    TOKEN_MODE_INFINITE,
]


CONF_NAME = "name"
CONF_LONG_NAME = "long_name"
CONF_ATTRIBUTION = "attribution"
CONF_AUTHOR = "author"
CONF_USES = "uses"
CONF_STATEMENTS = "statements"
CONF_ATTACHMENTS = "attachments"
CONF_FEEDBACK_LEVEL = "feedback_level"
CONF_SCORE_OPTIONS = "score_options"
CONF_DECIMAL_PLACES = "decimal_places"
CONF_MODE = "mode"
CONF_TYPE = "type"
CONF_OJUZ_KEY = "ojuz_key"
CONF_TIME_LIMIT = "time_limit"
CONF_MEMORY_LIMIT = "memory_limit"
CONF_SAMPLE_SOLUTION = "sample_solution"
CONF_GRADER = "grader"
CONF_TASK_TYPE = "task_type"
CONF_SUBTASKS = "subtasks"
CONF_POINTS = "points"
CONF_TESTCASES = "testcases"
CONF_INPUT = "input"
CONF_OUTPUT = "output"
CONF_CHECKER = "checker"
CONF_TEST_SUBMISSIONS = "test_submissions"
CONF_EXTENDS = "extends"
CONF_GCC_ARGS = "gcc_args"
CONF_LATEX_CONFIG = "latex_config"
CONF_LATEXMK_ARGS = "latexmk_args"
CONF_ADDITIONAL_FILES = "additional_files"
CONF_CPP_CONFIG = "cpp_config"
CONF_INPUT_TEMPLATE = "input_template"
CONF_PUBLIC = "public"
CONF_TOKENS = "tokens"
CONF_MAX_NUMBER = "max_number"
CONF_INITIAL = "initial"
CONF_GEN_NUMBER = "gen_number"
CONF_NUM_PROCESSES = "num_processes"
CONF_MANAGER = "manager"
CONF_CODENAME = "codename"
CONF_TESTCASE_CHECKER = "testcase_checker"
CONF_USER_IO = "user_io"
